CREATE TABLE IF NOT EXISTS users (
  user_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(150) NOT NULL,
  phone VARCHAR(30) NOT NULL UNIQUE,
  email VARCHAR(255) UNIQUE,
  role VARCHAR(30) NOT NULL CHECK (role IN ('CUSTOMER', 'DRIVER', 'OPERATION_STAFF')),
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  password_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
