CREATE TABLE IF NOT EXISTS trip_history (trip_id UUID PRIMARY KEY, status VARCHAR(30) NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS payment_history (payment_id UUID PRIMARY KEY, amount NUMERIC(12,2) NOT NULL, status VARCHAR(20) NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
